### ISSUE TITLE
Subrutina_Fuerzas (Estoy probando como van los Issues)

### ISSUE THREAD

**Issue by dani11torres** [Eines-Informatiques-Avancades/Project-II#2]
Esta subrutina necesita llamar a: pbc(dr,length), siendo dr la distancia entre dos partículas y length la longitud de la caja. Por lo que si el encargado de las pbc lo llama de otra forma debería cambiarse en dicha subrutina.

**Comment by altepi97** [comment]
Las pbc las lleva Adrià, pero diría que están implementadas como dices.
